image: gitpod/workspace-mysql

tasks:
  - init: mkdir .env && wget -c https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.tar.gz -O - | tar -xz -C .env
    command: php -S localhost:8000 -t .env/phpMyAdmin-5.0.2-all-languages
